/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminDashboard;

import config.config;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import main.landingPage;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author USER25
 */
public class accounts extends javax.swing.JFrame {

    public accounts(String names, String emails) {
        initComponents();
        name.setText(names);
        email.setText(emails);
        displayU();
    }

    private accounts() {

    }

    void displayU() {
        config con = new config();
        String sql = "SELECT u_id, u_name, u_email, u_status, u_type FROM tbl_user";
        con.displayData(sql, tableAccounts);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        backg = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAccounts = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtSearchField = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        back = new javax.swing.JPanel();
        approveacc = new javax.swing.JPanel();
        approve = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        account = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        email = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backg.setBackground(new java.awt.Color(237, 241, 249));
        backg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(237, 241, 249));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(96, 190, 220));
        jLabel2.setText("ACCOUNTS");
        backg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 190, 50));

        jLabel4.setBackground(new java.awt.Color(237, 241, 249));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(237, 241, 249));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        backg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, -1));

        tableAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableAccounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAccountsMouseClicked(evt);
            }
        });
        tableAccounts.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tableAccountsCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tableAccountsInputMethodTextChanged(evt);
            }
        });
        tableAccounts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tableAccountsKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tableAccounts);

        backg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 200, 500, 240));

        jLabel6.setBackground(new java.awt.Color(237, 241, 249));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(96, 190, 220));
        jLabel6.setText(" ADMIN DASHBOARD");
        backg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 190, 50));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        backg.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 30));

        jButton2.setText("Delete");
        backg.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, 30));

        jButton3.setText("Update");
        backg.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, 30));

        txtSearchField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchFieldActionPerformed(evt);
            }
        });
        txtSearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchFieldKeyTyped(evt);
            }
        });
        backg.add(txtSearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 160, 30));

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        backg.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, 30));

        getContentPane().add(backg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 560, 500));

        back.setBackground(new java.awt.Color(96, 190, 220));
        back.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        approveacc.setBackground(new java.awt.Color(96, 190, 220));

        approve.setBackground(new java.awt.Color(237, 241, 249));
        approve.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        approve.setText("PROFILE");
        approve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                approveMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout approveaccLayout = new javax.swing.GroupLayout(approveacc);
        approveacc.setLayout(approveaccLayout);
        approveaccLayout.setHorizontalGroup(
            approveaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(approveaccLayout.createSequentialGroup()
                .addComponent(approve, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        approveaccLayout.setVerticalGroup(
            approveaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(approveaccLayout.createSequentialGroup()
                .addComponent(approve, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        back.add(approveacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        back.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        logout.setBackground(new java.awt.Color(96, 190, 220));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(237, 241, 249));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("LOG OUT");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        back.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 200, 40));

        account.setBackground(new java.awt.Color(96, 190, 220));

        jLabel8.setBackground(new java.awt.Color(237, 241, 249));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("ACCOUNTS");

        javax.swing.GroupLayout accountLayout = new javax.swing.GroupLayout(account);
        account.setLayout(accountLayout);
        accountLayout.setHorizontalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        accountLayout.setVerticalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        back.add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 200, 40));

        name.setBackground(new java.awt.Color(237, 241, 249));
        name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("USER");
        back.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 220, 30));

        email.setBackground(new java.awt.Color(237, 241, 249));
        email.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email.setText("EMAIL");
        back.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 220, 30));

        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void approveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approveMouseEntered
        approve.setBackground(new java.awt.Color(10, 37, 64));
    }//GEN-LAST:event_approveMouseEntered

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        landingPage back = new landingPage();
        back.setLocationRelativeTo(null);
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        if (!logout.isEnabled()) {
            logout.setBackground(new java.awt.Color(10, 37, 64));
        }
    }//GEN-LAST:event_logoutMouseEntered

    private void tableAccountsCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tableAccountsCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tableAccountsCaretPositionChanged

    private void tableAccountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAccountsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableAccountsMouseClicked

    private void tableAccountsInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tableAccountsInputMethodTextChanged

    }//GEN-LAST:event_tableAccountsInputMethodTextChanged

    private void tableAccountsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableAccountsKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tableAccountsKeyTyped

    private void txtSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String findings = txtSearchField.getText();
        
        config con = new config();
        
        String sql = "SELECT u_id, u_name, u_email, u_status, u_type FROM tbl_user WHERE u_name = '" + findings + "' OR u_email = '" + findings + "' OR u_id = '" + findings + "' ";
        con.displayData(sql, tableAccounts);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtSearchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchFieldKeyTyped
        String searchText = txtSearchField.getText();
        String sql = "SELECT * FROM tbl_user WHERE u_id LIKE ? OR u_name LIKE ? OR u_email LIKE ? OR u_status LIKE ?";
        config conf = new config();
        conf.displayData(sql, tableAccounts, "%" + searchText + "%", "%" + searchText + "%", "%" + searchText + "%", "%" + searchText + "%");
    }//GEN-LAST:event_txtSearchFieldKeyTyped

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accounts.class

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accounts.class

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accounts.class

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accounts.class

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accounts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel account;
    private javax.swing.JLabel approve;
    private javax.swing.JPanel approveacc;
    private javax.swing.JPanel back;
    private javax.swing.JPanel backg;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel logout;
    private javax.swing.JLabel name;
    private javax.swing.JTable tableAccounts;
    private javax.swing.JTextField txtSearchField;
    // End of variables declaration//GEN-END:variables
}
