/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminDashboard;

import config.UserSession;
import config.config;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import main.login;
import managerDashboard.Managerdashboard;
import supplierDashboard.Supplierdashboard;

/**
 *
 * @author USER25
 */
public class editProf extends javax.swing.JFrame {

    /**
     * Creates new form editProf
     */
    private String path = "";

    public editProf() {
        if (UserSession.getU_id() == 0) {
            JOptionPane.showMessageDialog(null, "Access Denied! Please Login First.");

            login login = new login();
            login.setVisible(true);
            login.setLocationRelativeTo(null);
            this.dispose();
            return;
        }

        initComponents();
        this.setLocationRelativeTo(null);

        jTextField2.setText(UserSession.getInstance().getU_name());
        jTextField3.setText(UserSession.getInstance().getU_email());

        String existingPath = UserSession.getInstance().getImagePath();
        if (existingPath != null && !existingPath.isEmpty()) {
            config con = new config();
            con.setProfileIcon(Pic, existingPath);
            this.path = existingPath;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        name2 = new javax.swing.JLabel();
        email2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Pic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(237, 241, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setForeground(new java.awt.Color(44, 62, 80));

        jToggleButton2.setBackground(new java.awt.Color(51, 51, 51));
        jToggleButton2.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setText("DASHBOARD");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(682, Short.MAX_VALUE)
                .addComponent(jToggleButton2)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 50));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(44, 62, 80));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EDIT PROFILE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, 230, 40));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 230, 30));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 230, 30));

        jToggleButton1.setBackground(new java.awt.Color(44, 62, 80));
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("CONFIRM");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 120, 30));

        name2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        name2.setForeground(new java.awt.Color(44, 62, 80));
        name2.setText("NAME:");
        jPanel1.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        email2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        email2.setForeground(new java.awt.Color(44, 62, 80));
        email2.setText("EMAIL:");
        jPanel1.add(email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));

        jButton1.setBackground(new java.awt.Color(44, 62, 80));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SELECT IMAGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 120, -1));

        Pic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        Pic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 62, 80), 3));
        jPanel1.add(Pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 120, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        int userId = UserSession.getInstance().getU_id();

        String name = jTextField2.getText().trim();
        if (name.isEmpty()) {
            name = UserSession.getInstance().getU_name();
        }

        String finalPath = (this.path == null || this.path.isEmpty())
                ? UserSession.getInstance().getImagePath()
                : this.path;

        config conf = new config();

        int confirm = JOptionPane.showConfirmDialog(null, "Confirm changes to your profile?", "Update", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            String sql = "UPDATE tbl_user SET u_name = ?, u_image = ? WHERE u_id = ?";
            conf.updateRecord(sql, name, finalPath, userId);

            UserSession sess = UserSession.getInstance();
            sess.setU_name(name);
            sess.setImagePath(finalPath);

            JOptionPane.showMessageDialog(null, "Profile Updated Successfully!");

            String userType = sess.getU_type();
            if (userType.equalsIgnoreCase("Admin")) {
                Admindashboard admin = new Admindashboard();
                admin.setVisible(true);
            } else if (userType.equalsIgnoreCase("Manager")) {
                managerDashboard.Managerdashboard manager = new managerDashboard.Managerdashboard();
                manager.setVisible(true);
            } else {
                supplierDashboard.Supplierdashboard supplier = new supplierDashboard.Supplierdashboard();
                supplier.setVisible(true);
            }

            this.dispose();
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        Admindashboard back = new Admindashboard();
        back.setLocationRelativeTo(null);
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked

    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();

            try {
                BufferedImage original = ImageIO.read(f);

                BufferedImage resized = new BufferedImage(100, 100, BufferedImage.TYPE_INT_ARGB);

                Graphics2D g2d = resized.createGraphics();
                g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
                g2d.drawImage(original, 0, 0, 100, 100, null);
                g2d.dispose();

                File dir = new File("src/images");
                if (!dir.exists()) {
                    dir.mkdirs();
                }

                String fileName = "profile_" + System.currentTimeMillis() + ".png";
                File savedFile = new File(dir, fileName);

                ImageIO.write(resized, "png", savedFile);

                path = "src/images/" + fileName;

                Pic.setIcon(new ImageIcon(resized));

                System.out.println("Image saved successfully to: " + path);

            } catch (IOException ex) {
                Logger.getLogger(editProf.class
                        .getName()).log(Level.SEVERE, "Error saving profile image", ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pic;
    private javax.swing.JLabel email2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel name2;
    // End of variables declaration//GEN-END:variables
}
