/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminDashboard;

import config.UserSession;
import config.config;
import javax.swing.JOptionPane;
import main.login;

/**
 *
 * @author jhond
 */
public class logs extends javax.swing.JFrame {

    /**
     * Creates new form logs
     */
    public logs() {
        if (UserSession.getU_id() == 0) {
            JOptionPane.showMessageDialog(null, "Access Denied! Please Login First.");
            login login = new login();
            login.setVisible(true);
            login.setLocationRelativeTo(null);
            this.dispose();
            return;
        }

        initComponents();
        this.setLocationRelativeTo(null);

        name.setText(UserSession.getU_name());
        email.setText(UserSession.getU_email());

        config con = new config();
        String currentImagePath = UserSession.getImagePath();

        if (currentImagePath != null && !currentImagePath.isEmpty()) {
            con.setProfileIcon(image, currentImagePath);
        }

        displayLogs();
    }

    public void displayLogs() {
        config conf = new config();
        String sql = "SELECT u.u_name AS 'User Name', "
                + "s.login_time AS 'Login Time', "
                + "s.logout_time AS 'Logout Time', "
                + "s.s_status AS 'Status' "
                + "FROM tbl_user_sessions s "
                + "JOIN tbl_user u ON s.u_id = u.u_id "
                + "ORDER BY s.login_time DESC";

        conf.displayData(sql, jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        line = new javax.swing.JLabel();
        line1 = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        prods = new javax.swing.JLabel();
        accs = new javax.swing.JLabel();
        profs = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel11.setBackground(new java.awt.Color(237, 241, 249));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(237, 241, 249));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(96, 190, 220));
        jLabel2.setText("LOGS");
        jPanel11.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 190, 50));

        jLabel4.setBackground(new java.awt.Color(237, 241, 249));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(237, 241, 249));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel11.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel11.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 360));

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        jPanel3.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        email.setBackground(new java.awt.Color(237, 241, 249));
        email.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        email.setForeground(new java.awt.Color(237, 241, 249));
        email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email.setText("EMAIL");
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 220, 30));

        name.setBackground(new java.awt.Color(237, 241, 249));
        name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(237, 241, 249));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("USER");
        jPanel3.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 220, 30));

        line.setForeground(new java.awt.Color(255, 255, 255));
        line.setText("____________________________________");
        jPanel3.add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        line1.setForeground(new java.awt.Color(255, 255, 255));
        line1.setText("____________________________________");
        jPanel3.add(line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        dashboard.setBackground(new java.awt.Color(237, 241, 249));
        dashboard.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dashboard.setForeground(new java.awt.Color(237, 241, 249));
        dashboard.setText("Dashboard");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardMouseExited(evt);
            }
        });
        jPanel3.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 160, 30));

        prods.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        prods.setForeground(new java.awt.Color(237, 241, 249));
        prods.setText("Products");
        prods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prodsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prodsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prodsMouseExited(evt);
            }
        });
        jPanel3.add(prods, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 160, 30));

        accs.setBackground(new java.awt.Color(237, 241, 249));
        accs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        accs.setForeground(new java.awt.Color(237, 241, 249));
        accs.setText("Accounts");
        accs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accsMouseExited(evt);
            }
        });
        jPanel3.add(accs, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 160, 30));

        profs.setBackground(new java.awt.Color(237, 241, 249));
        profs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        profs.setForeground(new java.awt.Color(237, 241, 249));
        profs.setText("Profile");
        profs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profsMouseExited(evt);
            }
        });
        jPanel3.add(profs, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 160, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(237, 241, 249));
        jLabel1.setText("Logs");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 160, 30));

        jLabel5.setBackground(new java.awt.Color(237, 241, 249));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(237, 241, 249));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Log Out");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        Admindashboard dash = new Admindashboard();
        dash.setLocationRelativeTo(null);
        dash.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardMouseClicked

    private void dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseEntered
        dashboard.setBackground(new java.awt.Color(26, 188, 156));
        dashboard.setOpaque(true);
    }//GEN-LAST:event_dashboardMouseEntered

    private void dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseExited
        dashboard.setBackground(new java.awt.Color(44, 62, 80));
    }//GEN-LAST:event_dashboardMouseExited

    private void prodsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodsMouseClicked
        products prod = new products();
        prod.setLocationRelativeTo(null);
        prod.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_prodsMouseClicked

    private void prodsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodsMouseEntered
        prods.setBackground(new java.awt.Color(26, 188, 156));
        prods.setOpaque(true);
    }//GEN-LAST:event_prodsMouseEntered

    private void prodsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodsMouseExited
        prods.setBackground(new java.awt.Color(44, 62, 80));
    }//GEN-LAST:event_prodsMouseExited

    private void accsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accsMouseClicked
        accounts acc = new accounts();
        acc.setLocationRelativeTo(null);
        acc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accsMouseClicked

    private void accsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accsMouseEntered
        accs.setBackground(new java.awt.Color(26, 188, 156));
        accs.setOpaque(true);
    }//GEN-LAST:event_accsMouseEntered

    private void accsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accsMouseExited
        accs.setBackground(new java.awt.Color(44, 62, 80));
    }//GEN-LAST:event_accsMouseExited

    private void profsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profsMouseClicked
        profile prof = new profile();
        prof.setLocationRelativeTo(null);
        prof.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profsMouseClicked

    private void profsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profsMouseEntered
        profs.setBackground(new java.awt.Color(26, 188, 156));
        profs.setOpaque(true);
    }//GEN-LAST:event_profsMouseEntered

    private void profsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profsMouseExited
        profs.setBackground(new java.awt.Color(44, 62, 80));
    }//GEN-LAST:event_profsMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        logs log = new logs();
        log.setLocationRelativeTo(null);
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setBackground(new java.awt.Color(26, 188, 156));
        jLabel1.setOpaque(true);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        jLabel1.setBackground(new java.awt.Color(44, 62, 80));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        config conf = new config();
        try {

            String sql = "UPDATE tbl_user_sessions SET logout_time = datetime('now', 'localtime'), " + "s_status = 'Logged Out' " + "WHERE u_id = ? AND s_status = 'Online'";

            conf.updateRecord(sql, UserSession.getU_id());
        } catch (Exception e) {
            System.out.println("Logout Database Error: " + e.getMessage());
        }

        UserSession.clearSession();

        login out = new login();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setBackground(new java.awt.Color(255, 51, 51));
        jLabel5.setOpaque(true);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setBackground(new java.awt.Color(44, 62, 80));
    }//GEN-LAST:event_jLabel5MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accs;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel email;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel line;
    private javax.swing.JLabel line1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel prods;
    private javax.swing.JLabel profs;
    // End of variables declaration//GEN-END:variables
}
