/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managerDashboard;

import config.UserSession;
import config.config;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.login;

/**
 *
 * @author jhond
 */
public class addOrder extends javax.swing.JFrame {

    public addOrder() {
        if (UserSession.getU_id() == 0) {
            JOptionPane.showMessageDialog(null, "Access Denied! Please Login First.");
            login login = new login();
            login.setVisible(true);
            login.setLocationRelativeTo(null);
            this.dispose();
            return;
        }

        initComponents();
        this.setLocationRelativeTo(null);

        name.setText(UserSession.getU_name());
        email.setText(UserSession.getU_email());
        config con = new config();
        con.setProfileIcon(image, UserSession.getImagePath());

        txtID.setEditable(false);
        txtName.setEditable(false);
        txtCategory.setEditable(false);
        txtSize.setEditable(false);
        txtColor.setEditable(false);
        txtPrice.setEditable(false);
        jTextField2.setEditable(false);

        displayItems();
    }

    void displayItems() {
        config con = new config();
        String sql = "SELECT * FROM tbl_items";
        con.displayData(sql, items);

        items.getColumnModel().getColumn(0).setPreferredWidth(50);
        items.getColumnModel().getColumn(1).setPreferredWidth(140);
        items.getColumnModel().getColumn(3).setPreferredWidth(50);
        items.getColumnModel().getColumn(4).setPreferredWidth(70);
        items.getColumnModel().getColumn(5).setPreferredWidth(75);
        items.getColumnModel().getColumn(6).setPreferredWidth(50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        line = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        view = new javax.swing.JLabel();
        update = new javax.swing.JLabel();
        remove = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        line1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        items = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        txtID = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();
        txtSize = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(44, 62, 80));
        jPanel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        jPanel10.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        name.setBackground(new java.awt.Color(237, 241, 249));
        name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(237, 241, 249));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("USER");
        jPanel10.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 220, 30));

        email.setBackground(new java.awt.Color(237, 241, 249));
        email.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        email.setForeground(new java.awt.Color(237, 241, 249));
        email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email.setText("EMAIL");
        jPanel10.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 220, 30));

        line.setForeground(new java.awt.Color(255, 255, 255));
        line.setText("____________________________________");
        jPanel10.add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        add.setBackground(new java.awt.Color(237, 241, 249));
        add.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        add.setForeground(new java.awt.Color(236, 240, 241));
        add.setText("Add Supply Order");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        jPanel10.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 190, 30));

        view.setBackground(new java.awt.Color(237, 241, 249));
        view.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        view.setForeground(new java.awt.Color(236, 240, 241));
        view.setText("View All Supply Order");
        view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewMouseExited(evt);
            }
        });
        jPanel10.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 190, 30));

        update.setBackground(new java.awt.Color(237, 241, 249));
        update.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        update.setForeground(new java.awt.Color(236, 240, 241));
        update.setText("Update Supply Order");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        jPanel10.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 190, 30));

        remove.setBackground(new java.awt.Color(237, 241, 249));
        remove.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        remove.setForeground(new java.awt.Color(237, 241, 249));
        remove.setText("Remove Order");
        remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeMouseExited(evt);
            }
        });
        jPanel10.add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 190, 30));

        profile.setBackground(new java.awt.Color(237, 241, 249));
        profile.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        profile.setForeground(new java.awt.Color(237, 241, 249));
        profile.setText("Profile");
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileMouseExited(evt);
            }
        });
        jPanel10.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 190, 30));

        jLabel5.setBackground(new java.awt.Color(237, 241, 249));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(237, 241, 249));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Log Out");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 200, 40));

        line1.setForeground(new java.awt.Color(255, 255, 255));
        line1.setText("____________________________________");
        jPanel10.add(line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 500));

        jPanel11.setBackground(new java.awt.Color(248, 249, 250));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(237, 241, 249));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(44, 62, 80));
        jLabel2.setText("ADD SUPPLY ORDER");
        jPanel11.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 230, 50));

        jLabel4.setBackground(new java.awt.Color(237, 241, 249));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(237, 241, 249));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel11.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 170, -1));

        items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        items.getTableHeader().setReorderingAllowed(false);
        items.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(items);

        jPanel11.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 520, 120));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel11.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 190, 30));

        jToggleButton1.setBackground(new java.awt.Color(44, 62, 80));
        jToggleButton1.setForeground(new java.awt.Color(248, 249, 250));
        jToggleButton1.setText("SEARCH");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel11.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, 30));
        jPanel11.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 160, 30));
        jPanel11.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 160, 30));
        jPanel11.add(txtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 160, 30));
        jPanel11.add(txtSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 160, 30));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel11.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 160, 30));
        jPanel11.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 160, 30));

        jLabel1.setText("SUPPLIER:");
        jPanel11.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        jToggleButton2.setBackground(new java.awt.Color(44, 62, 80));
        jToggleButton2.setForeground(new java.awt.Color(248, 249, 250));
        jToggleButton2.setText("Add Order");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel11.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 100, 30));

        jLabel7.setText("SIZE:");
        jPanel11.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        jLabel10.setText("ID:");
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jLabel15.setText(" NAME:");
        jPanel11.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jLabel16.setText("CATEGORY:");
        jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel18.setText("COLOR:");
        jPanel11.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        jLabel20.setText("PRICE:");
        jPanel11.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));
        jPanel11.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 80, 30));

        jToggleButton3.setBackground(new java.awt.Color(44, 62, 80));
        jToggleButton3.setForeground(new java.awt.Color(248, 249, 250));
        jToggleButton3.setText("DASHBOARD");
        jToggleButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton3MouseClicked(evt);
            }
        });
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel11.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jLabel3.setText("QUANTITY:");
        jPanel11.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, -1, -1));
        jPanel11.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 160, 30));

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 570, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        String findings = jTextField1.getText();

        config con = new config();

        String sql = "SELECT i_id, i_name, i_category FROM tbl_items WHERE i_name = '" + findings + "' OR i_category = '" + findings + "' OR i_id = '" + findings + "' ";
        con.displayData(sql, items);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped

    }//GEN-LAST:event_jTextField1KeyTyped

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) items.getModel();
        int selectedRow = items.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a product from the table first!", "Selection Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Object supplierID = jTextField2.getClientProperty("supplier_id");
        String supplierName = jTextField2.getText();

        if (supplierName == null || supplierName.trim().isEmpty() || supplierName.equalsIgnoreCase("No Supplier Available") || supplierID == null) {
            JOptionPane.showMessageDialog(null, "Cannot process order: No Supplier Available for this item!", "Supplier Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int requestedQty = Integer.parseInt(jSpinner1.getValue().toString());
        int availableStock = Integer.parseInt(model.getValueAt(selectedRow, 6).toString());

        if (requestedQty <= 0) {
            JOptionPane.showMessageDialog(null, "Quantity must be greater than 0.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (requestedQty > availableStock) {
            JOptionPane.showMessageDialog(null, "Insufficient stock! Only " + availableStock + " items available.", "Stock Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        java.time.LocalDate today = java.time.LocalDate.now();
        String orderDate = today.toString();
        String deliveryDate = today.plusDays(7).toString();
        String orderTime = java.time.LocalTime.now().format(java.time.format.DateTimeFormatter.ofPattern("hh:mm a"));

        String id = txtID.getText();
        String nam = txtName.getText();
        String cat = txtCategory.getText();
        String size = txtSize.getText();
        String color = txtColor.getText();
        double unitPrice = Double.parseDouble(txtPrice.getText());

        double totalAmount = unitPrice * requestedQty;

        config conf = new config();

        String sql = "INSERT INTO tbl_order (i_id, u_id, o_name, o_category, o_size, o_color, o_amountpay, o_quantity, o_deliverydate, o_status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        conf.addRecord(sql, id, supplierID, nam, cat, size, color, totalAmount, requestedQty, deliveryDate, "PENDING");

        String receipt = "            OSM SYSTEM - ORDER RECEIPT\n"
                + "------------------------------------------\n"
                + "Order Date:   " + orderDate + "\n"
                + "Delivery Due: " + deliveryDate + "\n"
                + "Time:         " + orderTime + "\n"
                + "Supplier:     " + supplierName + "\n"
                + "------------------------------------------\n"
                + "Product ID:   " + id + "\n"
                + "Item Name:    " + nam + "\n"
                + "Category:     " + cat + "\n"
                + "Size/Color:   " + size + " / " + color + "\n"
                + "------------------------------------------\n"
                + "Unit Price:   ₱" + String.format("%,.2f", unitPrice) + "\n"
                + "Quantity:     " + requestedQty + "\n"
                + "------------------------------------------\n"
                + "TOTAL AMOUNT: ₱" + String.format("%,.2f", totalAmount) + "\n"
                + "------------------------------------------\n"
                + "\nOrder Added Successfully!\nDo you want to make another order?";

        javax.swing.JTextArea textArea = new javax.swing.JTextArea(receipt);
        textArea.setEditable(false);
        textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
        scrollPane.setPreferredSize(new java.awt.Dimension(350, 400));

        int choice = JOptionPane.showConfirmDialog(null, scrollPane, "Order Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (choice == JOptionPane.YES_OPTION) {
            txtID.setText("");
            txtName.setText("");
            txtCategory.setText("");
            txtSize.setText("");
            txtColor.setText("");
            txtPrice.setText("");
            jSpinner1.setValue(0);
            jTextField2.setText("");
            displayItems();
        } else {
            Managerdashboard back = new Managerdashboard();
            back.setVisible(true);
            back.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String searchText = jTextField1.getText();
        String sql = "SELECT * FROM tbl_items WHERE i_id LIKE ? OR i_name LIKE ? OR i_category LIKE ?";
        config conf = new config();
        conf.displayData(sql, items, "%" + searchText + "%", "%" + searchText + "%", "%" + searchText + "%");
    }//GEN-LAST:event_jTextField1KeyReleased

    private void itemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsMouseClicked
        DefaultTableModel model = (DefaultTableModel) items.getModel();
        int selectedRow = items.getSelectedRow();

        String itemId = model.getValueAt(selectedRow, 0).toString();
        txtID.setText(itemId);
        txtName.setText(model.getValueAt(selectedRow, 1).toString());
        txtCategory.setText(model.getValueAt(selectedRow, 2).toString());
        txtSize.setText(model.getValueAt(selectedRow, 3).toString());
        txtColor.setText(model.getValueAt(selectedRow, 4).toString());
        String price = model.getValueAt(selectedRow, 5).toString().replace("₱", "").replace(",", "");
        txtPrice.setText(price);

        int stock = Integer.parseInt(model.getValueAt(selectedRow, 6).toString());
        javax.swing.SpinnerNumberModel spinnerModel = new javax.swing.SpinnerNumberModel(0, 0, stock, 1);
        jSpinner1.setModel(spinnerModel);

        try {
            config db = new config();
            String itemQry = "SELECT i_company FROM tbl_items WHERE i_id = '" + itemId + "'";
            java.util.List<java.util.Map<String, Object>> itemData = db.fetchRecords(itemQry);

            if (!itemData.isEmpty()) {
                String company = itemData.get(0).get("i_company").toString();
                String supplierQry = "SELECT u_id, u_name FROM tbl_user "
                        + "WHERE u_company = '" + company + "' "
                        + "AND u_type = 'Supplier' "
                        + "ORDER BY RANDOM() LIMIT 1";

                java.util.List<java.util.Map<String, Object>> supplierData = db.fetchRecords(supplierQry);

                if (!supplierData.isEmpty()) {
                    Object sID = supplierData.get(0).get("u_id");
                    String sName = supplierData.get(0).get("u_name").toString();
                    jTextField2.setText(sName);
                    jTextField2.putClientProperty("supplier_id", sID);
                } else {
                    jTextField2.setText("No Supplier Found");
                    jTextField2.putClientProperty("supplier_id", null);
                }
            }
        } catch (Exception e) {
            System.out.println("Error fetching supplier: " + e.getMessage());
        }
    }//GEN-LAST:event_itemsMouseClicked

    private void jToggleButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton3MouseClicked
        Managerdashboard dash = new Managerdashboard();
        dash.setLocationRelativeTo(null);
        dash.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButton3MouseClicked

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        addOrder order = new addOrder();
        order.setLocationRelativeTo(null);
        order.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setBackground(new java.awt.Color(26, 188, 156));
        add.setOpaque(true);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(new java.awt.Color(44, 62, 80));
    }//GEN-LAST:event_addMouseExited

    private void viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseClicked
        ViewOrders view = new ViewOrders();
        view.setLocationRelativeTo(null);
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewMouseClicked

    private void viewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseEntered
        view.setBackground(new java.awt.Color(26, 188, 156));
        view.setOpaque(true);
    }//GEN-LAST:event_viewMouseEntered

    private void viewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseExited
        view.setBackground(new java.awt.Color(44, 62, 80));
    }//GEN-LAST:event_viewMouseExited

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        UpdateOrder update = new UpdateOrder();
        update.setLocationRelativeTo(null);
        update.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updateMouseClicked

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        update.setBackground(new java.awt.Color(26, 188, 156));
        update.setOpaque(true);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        update.setBackground(new java.awt.Color(44, 62, 80));
    }//GEN-LAST:event_updateMouseExited

    private void removeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMouseClicked
        DeleteOrder delete = new DeleteOrder();
        delete.setLocationRelativeTo(null);
        delete.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_removeMouseClicked

    private void removeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMouseEntered
        remove.setBackground(new java.awt.Color(26, 188, 156));
        remove.setOpaque(true);
    }//GEN-LAST:event_removeMouseEntered

    private void removeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMouseExited
        remove.setBackground(new java.awt.Color(44, 62, 80));
    }//GEN-LAST:event_removeMouseExited

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        managerProfile profile = new managerProfile();
        profile.setLocationRelativeTo(null);
        profile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileMouseClicked

    private void profileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseEntered
        profile.setBackground(new java.awt.Color(26, 188, 156));
        profile.setOpaque(true);
    }//GEN-LAST:event_profileMouseEntered

    private void profileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseExited
        profile.setBackground(new java.awt.Color(44, 62, 80));
    }//GEN-LAST:event_profileMouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        UserSession.clearSession();

        login out = new login();
        out.setLocationRelativeTo(null);
        out.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setBackground(new java.awt.Color(255, 51, 51));
        jLabel5.setOpaque(true);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setBackground(new java.awt.Color(44, 62, 80));
    }//GEN-LAST:event_jLabel5MouseExited

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JLabel email;
    private javax.swing.JLabel image;
    private javax.swing.JTable items;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JLabel line;
    private javax.swing.JLabel line1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel remove;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSize;
    private javax.swing.JLabel update;
    private javax.swing.JLabel view;
    // End of variables declaration//GEN-END:variables
}
